### ISSUE TITLE
"PadToJoy" for some games like Portal 2?

### ISSUE THREAD

**Issue by giuliano-macedo** [UniversalSplitScreen/UniversalSplitScreen#23]
So, i was trying to make Portal 2 work split screen with keyboard+mouse, however it does not have LAN functionality, but it does have native offline split screen, but it requires a controller, it shows up "press X on controller to play", therefore i think it is a good ideia to implement a feature that emulates keyboard+mouse as gamepad in the same window handle that another keyboard is hooked normally in the project....

**Comment by Udinanon** [comment]
Portal does support LAN play tho, you just gotta launch it with the sv_lan command
source: https://www.pcgamingwiki.com/wiki/Portal_2#Network

**Comment by giuliano-macedo** [comment]
there is a solution in 
https://www.pcgamingwiki.com/wiki/Portal_2#Split-screen_co-op
