### ISSUE TITLE
not technically an issue but it is much needed

### ISSUE THREAD

**Issue by hodayfa000-h** [UniversalSplitScreen/UniversalSplitScreen#92]
so the issue is that this program does not support virtual mice/keyboards which means it can't split screen games that use only keyboards USING a controller if that makes sense (remapping gamepad to a virtual keyboard it does not detect it) i am guessing it isn't a simple thing to fix is it?

**Comment by SolidSouless** [comment]
You could try using a program called [KeyboardSplitter](https://www.softpedia.com/get/System/System-Miscellaneous/Gaming-Keyboard-Splitter.shtml). It's an old program, that I have used on and off, though I have never needed to use it with Universal split screen as I just prefer controller. It may provide the functionality you are looking for. If that doesn't do it, you could try alternatively or in combination, a program called [KeystoXInput](https://www.embenco.nl/keys2xinput/). Again, I've only used in isolation, but they technically can work together to allow a keyboard to act as a virtual gamepad, or a game pad to work as a virtual keyboard.

**Comment by hodayfa000-h** [comment]
Thanks!
